databases:
  - name: blog_projectdb
    plan: free
    databaseName: blog_project
    user: blog_project

services:
  - type: web
    plan: free
    name: blog_project
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m uvicorn mysite.asgi:application --workers 4'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog_projectdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4