# Generated by Django 5.2.3 on 2025-06-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='public_blog',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(default='No description'),
        ),
    ]
