# Generated by Django 5.2.3 on 2025-06-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0002_blog_public_blog_alter_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.CharField(default='No title', max_length=200),
        ),
    ]
